import { IAnswer } from '@ui/models/question';

export const MOCK_TEMP_LIST_ANSWER: IAnswer[] = [
  {
    id: -1,
    text: '',
    index: 0,
    correct: false,
    explanation: '',
    type: 'learn',
    parentId: -1,
    turn: 1,
    isSynced: false,
  },
  {
    id: -2,
    text: '',
    isSynced: false,
    index: 0,
    correct: false,
    explanation: '',
    type: 'learn',
    parentId: -1,
    turn: 1,
  },
  {
    id: -3,
    isSynced: false,
    text: '',
    index: 0,
    correct: false,
    explanation: '',
    type: 'learn',
    parentId: -1,
    turn: 1,
  },
  {
    id: -4,
    isSynced: false,
    text: '',
    index: 0,
    correct: false,
    explanation: '',
    type: 'learn',
    parentId: -1,
    turn: 1,
  },
];
