export const API_PATH = {
  APP_INFO: '/api/appInfos',
  APP_CONFIG: '/api/appConfig',
  GET_SEO: '/api/getSeo',
  GET_DATA_STUDY: '/api/study',
  GET_DATA_STATE: '/api/state',
  GET_DATA_TOPICS: '/api/topics',
  GET_QUESTION_BY_ID: '/api/getQuestion',
  GET_APP_REVIEW: '/api/getAppReview',
  GET_LIST_BLOCK: '/api/getListBlock',
  REPORT_MISTAKE: '/api/question/update-report',
  SW_TOPIC: '/api/sw/topics',
  SW_PASSING: '/api/sw/passing',
  SW_TESTS: '/api/sw/tests',
  SW_QUESTION: '/api/sw/question',
};
