const appShortName = process.env['NEXT_PUBLIC_APP_SHORT_NAME'];
const RouterApp = {
  Home: '/',
  Get_pro: '/get-pro',
  Topics: '/topics',
  Finish: '/finish',
  About: '/about-us',
  Contacts: '/contact',
  Privacy: '/privacy',
  Refund_policy: 'refund-policy',
  Blog: '/blog',
  Teams_of_service: 'terms-of-service',
  Study_Guides: 'study-guide',
  Score_Calculator: 'score-calculator',
  Test: '/test',
  Review: '/review',
  ResultTest: '/result-test',
  Billing: '/billing',
  Edit_policy: 'editorial-policy',
  Diagnostic_test: '/diagnostic-test',
  Custom_test: '/custom-test',
  Final_test: `/full-length-${appShortName}-practice-tests`,
  Practice_Tests: '/practice-test',
  Study: '/study',
};
export default RouterApp;
