const RouterApp = {
  Home: '/',
  Get_pro: '/get-pro',
  Topics: '/topics',
  Finish: '/finish',
  About: '/about-us',
  Contacts: '/contact',
  Privacy: '/privacy',
  Refund_policy: '/refund-policy',
  Blog: '/blog',
  Teams_of_service: '/terms-of-service',
  Study_Guides: '/study-guide',
  Score_Calculator: '/score-calculator',
  Test: '/test',
  Review: '/review',
  ResultTest: '/result_test',
  Billing: '/billing',
  Edit_policy: '/editorial-policy',
  Diagnostic_test: '/diagnostic-test',
  Custom_test: '/custom-test',
  Final_test: '/final-test',
  Practice_Tests: '/practice_tests',
  Study: '/study',
};
export default RouterApp;
